import Head from 'next/head'
import Banner from '@/components/Banner/Banner'
import Contact from '@/components/Contact/Contact'
import Subscribe from '@/components/Subscribe/Subscribe'
import Footer from '@/components/Footer/Footer'
import styles from '../styles/Home.module.scss'

export default function Home (): JSX.Element {
  return (
    <>
      <Head>
        <title>Clothes shop - Home</title>
        <meta
          name={'description'}
          content={'Generated by create next app'}
        />
        <meta
          name={'viewport'}
          content={'width=device-width, initial-scale=1'}
        />
        <link
          rel={'icon'}
          href={'/favicon.ico'}
        />
      </Head>
      <section className={styles.wrapper}>
        <Banner />
      </section>
      <section className={styles.wrapper}>
        <Subscribe />
      </section>
      <section className={styles.wrapper}>
        <Contact />
      </section>
      <Footer />
    </>
  )
}
